-- Neon PostgreSQL Data Export from Local XAMPP MySQL
-- Generated for AgriFresh Connect

TRUNCATE TABLE activity_logs CASCADE;
TRUNCATE TABLE price_index CASCADE;
TRUNCATE TABLE order_items CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE buyers CASCADE;
TRUNCATE TABLE farmers CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE roles CASCADE;

-- Table: roles (3 rows)
INSERT INTO roles ("id", "name", "slug", "created_at") VALUES (1, 'Administrator', 'admin', '2026-09-02 20:37:05');
INSERT INTO roles ("id", "name", "slug", "created_at") VALUES (2, 'Farmer', 'farmer', '2026-09-02 20:37:05');
INSERT INTO roles ("id", "name", "slug", "created_at") VALUES (3, 'Buyer', 'buyer', '2026-09-02 20:37:05');
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE((SELECT MAX(id) FROM roles), 1));

-- Table: users (9 rows)
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (1, 1, 'Famox Admin (Lunas Hub)', 'admin@famox.my', 'password', '+60 19-400 1100', 'Famox Central Hub, Lunas, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (2, 2, 'Pak Cik Azman Bin Hashim', 'azman@ladangmakmur.my', 'Azman05#', '+60 19-482 9102', 'Ladang Hijau Makmur, Lunas, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (3, 2, 'Puan Siti Hajar Binti Ismail', 'sitihajar@kulimhydro.my', 'password', '+60 17-512 8841', 'Kebun Hidroponik Kulim, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (4, 2, 'Encik Tan Wei Loon', 'tan@balinggreen.my', 'password', '+60 12-441 3990', 'Baling Highland Agro, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (5, 2, 'Haji Roslan Ahmad', 'roslan@pokoksena.my', 'password', '+60 13-908 7215', 'Pokok Sena Eco Farm, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (6, 3, 'Muhammad Aizat (Buyer)', 'aizat@aimst.edu.my', 'password', '+60 19-334 8812', 'No. 12, Jalan Lunas Makmur 3, 09600 Lunas, Kedah', NULL, 1, '2026-09-02 20:37:05');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (7, 3, 'Muhammad Aizat Izzuddin', 'muhammadaizatizzuddin@gmail.com', 'Muhammadaziat01#', '019-8343847', 'Lot 19, Jalan Wawasan, Kampung Bendang Dalam, 08400 Merbok, Kedah.', NULL, 1, '2026-09-04 01:31:27');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (8, 2, 'Aina Izzati Binti Azmi', 'ainaizzatiazmi@gmail.com', 'Ainaizzati08#', '+60 19-334 8812', 'Lot 19, Jalan Wawasan, Kampung Bendang Dalam, 08400 Merbok, Kedah.', NULL, 1, '2026-09-04 01:47:08');
INSERT INTO users ("id", "role_id", "name", "email", "password", "phone", "address", "avatar", "is_active", "created_at") VALUES (9, 3, 'Paarteeban', 'parteeban123@gmail.com', 'parteeban123', '019-8343847', 'lot 129, jalan seroja, 08400 merbpok ,kedah', NULL, 1, '2026-09-11 10:35:25');
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));

-- Table: farmers (5 rows)
INSERT INTO farmers ("id", "user_id", "farm_name", "kedah_district", "farm_location_details", "farming_certification", "cert_number", "experience_years", "rating", "famox_tier", "avatar", "quote", "is_approved", "created_at") VALUES (1, 2, 'Ladang Hijau Makmur Lunas', 'Kulim / Lunas', 'Lunas, Kulim District, Kedah (5.4321° N, 100.5342° E)', 'MyGAP Certified', 'MYGAP-KDH-2024-0891', 16, 4.90, 'Platinum Supplier Partner', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80', 'With AgriFresh Connect and Famox, we get direct fair prices without middlemen squeezing our livelihood.', 1, '2026-09-02 20:37:05');
INSERT INTO farmers ("id", "user_id", "farm_name", "kedah_district", "farm_location_details", "farming_certification", "cert_number", "experience_years", "rating", "famox_tier", "avatar", "quote", "is_approved", "created_at") VALUES (2, 3, 'Kebun Sayur Hidroponik Kulim', 'Kulim', 'Kulim Hi-Tech Agro Valley, Kedah (5.3688° N, 100.5540° E)', 'Pesticide-Free Green Label', 'MYORG-KDH-2025-0143', 9, 4.80, 'Gold Supplier Partner', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80', 'My hydroponic lettuces and kailan reach school canteens and cafes within hours of morning harvest.', 1, '2026-09-02 20:37:05');
INSERT INTO farmers ("id", "user_id", "farm_name", "kedah_district", "farm_location_details", "farming_certification", "cert_number", "experience_years", "rating", "famox_tier", "avatar", "quote", "is_approved", "created_at") VALUES (3, 4, 'Baling Highland Foothills Agro', 'Baling', 'Baling, Kedah (5.6780° N, 100.9167° E)', 'MyGAP & Halal Supply Chain', 'MYGAP-KDH-2023-0442', 22, 5.00, 'Platinum Supplier Partner', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80', 'Traceability QR codes show customers the exact time our mountain corn and cabbages were plucked.', 1, '2026-09-02 20:37:05');
INSERT INTO farmers ("id", "user_id", "farm_name", "kedah_district", "farm_location_details", "farming_certification", "cert_number", "experience_years", "rating", "famox_tier", "avatar", "quote", "is_approved", "created_at") VALUES (4, 5, 'Pokok Sena Eco Farm', 'Pokok Sena / Alor Setar', 'Pokok Sena, Kedah (6.1667° N, 100.5167° E)', 'MyGAP Standard', 'MYGAP-KDH-2024-1102', 14, 4.90, 'Gold Supplier Partner', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80', 'Direct sales mean fresher food for our community and predictable income for our families.', 1, '2026-09-02 20:37:05');
INSERT INTO farmers ("id", "user_id", "farm_name", "kedah_district", "farm_location_details", "farming_certification", "cert_number", "experience_years", "rating", "famox_tier", "avatar", "quote", "is_approved", "created_at") VALUES (5, 8, 'Aina Suka Ria Farm', 'Merbok', 'Lunas, Kulim District, Kedah', 'Organic Green Label', 'MYGAP-KDH-2024-0891', 5, 4.90, 'Verified Supplier Partner', 'assets/img/uploads/avatar_1790044180_6035.jpeg', 'Fresh direct from farm to consumer with complete traceability.', 1, '2026-09-04 01:47:08');
SELECT setval(pg_get_serial_sequence('farmers', 'id'), COALESCE((SELECT MAX(id) FROM farmers), 1));

-- Table: buyers (2 rows)
INSERT INTO buyers ("id", "user_id", "company_name", "buyer_type", "created_at") VALUES (1, 7, 'Muhammad Aizat Izzuddin', 'Direct Consumer', '2026-09-04 01:31:27');
INSERT INTO buyers ("id", "user_id", "company_name", "buyer_type", "created_at") VALUES (2, 9, 'Paarteeban', 'Direct Consumer', '2026-09-11 10:35:25');
SELECT setval(pg_get_serial_sequence('buyers', 'id'), COALESCE((SELECT MAX(id) FROM buyers), 1));

-- Table: categories (7 rows)
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (1, 'All Harvests', 'Semua Hasil', 'all', '🌱', 'All fresh produce from Kedah farmers', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (2, 'Leafy Greens', 'Sayuran Daun', 'leafy', '🥬', 'Fresh daily harvested greens', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (3, 'Vine & Fruiting', 'Sayuran Buah', 'fruiting', '🍅', 'Fresh vine tomatoes and cucumbers', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (4, 'Chilies & Spices', 'Cili & Rempah', 'chilies', '🌶️', 'Authentic spicy Kedah chilies', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (5, 'Highlands & Corn', 'Tanah Tinggi & Jagung', 'tubers', '🌽', 'Highland corn and root crops', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (6, 'Curated Fresh Boxes', 'Kotak Segar Mingguan', 'bundles', '📦', 'Weekly family fresh boxes', '2026-09-02 20:37:05');
INSERT INTO categories ("id", "name", "name_ms", "slug", "icon", "description", "created_at") VALUES (7, 'Hydroponic & Organic', 'Hidroponik & Organik', 'hydroponic', '🌿', 'Clean pesticide-free crops', '2026-09-02 20:37:05');
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1));

-- Table: products (10 rows)
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (1, 'AF-LUN-2026-089', 1, 3, 'Lunas Sweet Roma Tomatoes', 'Lunas Sweet Roma Tomatoes', 'lunas-sweet-roma-tomatoes', 'Plump, sun-ripened Roma tomatoes harvested early this morning in Lunas, Kedah. Rich in lycopene and sweetness, ideal for fresh salads, sauces, and local curries.', 'Plump, sun-ripened Roma tomatoes harvested early this morning in Lunas, Kedah. Rich in lycopene and sweetness, ideal for fresh salads, sauces, and local curries.', '2026-09-02 05:30 AM', '2026-09-12', 0.00, 1.00, 'kg', 4.20, 6.30, '12°C - 15°C (Cool & Dry)', 'Lunas, Kedah', 'Grade A Premium', '0.00 ppm (Passed MyGAP Lab Test)', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80', 1, 'Sweet. Juicy. Picked at dawn.', 'Sun-ripened Roma tomatoes from Pak Cik Azman''s Lunas farm.', 'FRESH HARVEST TODAY', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (2, 'AF-KLM-2026-042', 2, 7, 'Hydroponic Butterhead Lettuce', 'Salad Butterhead Hidroponik', 'hydroponic-butterhead-lettuce', 'Tender, buttery leaves grown in temperature-controlled hydroponic channels with filtered deep-well water. Ready to eat with zero soil debris.', 'Daun lembut berkualiti tinggi yang ditanam dalam sistem hidroponik terkawal di Kulim. Sedia dimakan, bersih tanpa sisa tanah mahupun racun serangga.', '2026-09-02 06:00 AM', '2026-09-10', 160.00, 1.00, '250g pack', 4.50, 7.20, '4°C (Refrigerated)', 'Kulim Agro Valley, Kedah', 'Grade A Export Quality', '100% Pesticide Free (Indoor Hydroponics)', 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800&auto=format&fit=crop&q=80', 1, 'Crisp purity. Grown with science.', 'Clean hydroponic green leaves from Puan Siti Hajar in Kulim.', '100% PESTICIDE-FREE', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (3, 'AF-BLG-2026-115', 3, 5, 'Baling Mountain Sweet Honey Corn', 'Jagung Manis Madu Baling', 'baling-mountain-sweet-honey-corn', 'Extra sweet variety with vibrant yellow kernels. Plucked before sunrise when sugar levels peak. Delicious steamed or grilled.', 'Varieti jagung madu dengan kemanisan semula jadi yang tinggi. Dituai sebelum matahari terbit untuk mengekalkan kesegaran isi yang rangup dan manis.', '2026-09-02 04:45 AM', '2026-09-08', 500.00, 3.00, 'ear (tongkol)', 2.20, 3.80, 'Cool ventilated crate', 'Baling Foothills, Kedah', 'Grade A Super Sweet (16° Brix)', 'MyGAP Safe Certified', 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&auto=format&fit=crop&q=80', 1, 'Naturally sweet. Bursting with crunch.', 'Highland foothills honey corn harvested at dawn in Baling.', 'SWEETEST BATCH', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (4, 'AF-KLM-2026-077', 1, 4, 'Kedah Kulim Cili Padi Merah', 'Cili Padi Kampung Kulim', 'kedah-kulim-cili-padi-merah', 'Authentic Malaysian red bird''s eye chili from Kulim smallholders. High heat index, fragrant aroma, essential for sambal and Asian cooking.', 'Cili padi merah kampung asli dari pekebun kecil Kulim. Sangat pedas, beraroma harum, terbaik untuk sambal belacan dan hidangan pedas tempatan.', '2026-09-01 07:00 AM', '2026-09-20', 95.00, 0.50, 'kg', 12.00, 18.50, 'Dry cold 8°C', 'Kulim, Kedah', 'Grade A Extra Pungent', 'Organic Neem Oil Protected', 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80', 0, 'Fiery aroma straight from Kedah soil.', 'Authentic local bird''s eye chilies with supreme heat.', 'EXTRA SPICY', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (5, 'AF-FMX-2026-BOX1', 1, 6, 'Famox Weekly Harvest Box (6kg Bundle)', 'Kotak Segar Mingguan Famox (6kg)', 'famox-weekly-harvest-box', 'Curated weekly fresh box containing 1kg Roma Tomatoes, 1kg Butterhead Lettuce, 1kg Japanese Cucumbers, 1kg Sawi, 1kg Sweet Corn, and 1kg Long Beans. Perfect for a family of 4.', 'Kotak sayur segar mingguan lengkap: 1kg Tomato Roma, 1kg Salad Butterhead, 1kg Timun Jepun, 1kg Sawi Hijau, 1kg Jagung Manis, dan 1kg Kacang Panjang. Jimat untuk keluarga 4 orang.', '2026-09-02 05:00 AM', '2026-09-12', 75.00, 1.00, 'box (6kg assorted)', 28.00, 42.00, 'Keep Chilled', 'Famox Central Hub, Lunas Kedah', 'Multi-Farm Grade A Curated', 'All Farm Batches MyGAP Certified', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=800&auto=format&fit=crop&q=80', 1, 'A week of vibrant health in one box.', 'Assorted greens, vine tomatoes, sweet corn, and crisp cucumbers.', 'BEST VALUE BUNDLE', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (6, 'AF-PKS-2026-033', 4, 3, 'Pokok Sena Crispy Cucumbers', 'Timun Jepun Rangup Pokok Sena', 'pokok-sena-crispy-cucumbers', 'Crunchy, dark green Japanese cucumbers grown in rich compost soil. Excellent for salads, sushi, or refreshing detox water.', 'Timun Jepun hijau gelap yang rangup dan berair. Ditanam dengan baja kompos organik, sesuai untuk ulam, salad, dan jus detoks.', '2026-09-02 05:15 AM', '2026-09-15', 210.00, 1.00, 'kg', 3.50, 5.20, '8°C - 10°C', 'Pokok Sena, Kedah', 'Grade A Seedless Crisp', 'MyGAP Tested 0 Residue', 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=800&auto=format&fit=crop&q=80', 0, '96% pure hydration from Kedah soil.', 'Thin skinned and seedless Japanese cucumbers.', 'HYDRATING & CRISP', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (7, 'AF-LUN-2026-012', 1, 2, 'Lunas Fresh Sawi Hijau (Choy Sum)', 'Sawi Hijau Manis Lunas', 'lunas-fresh-sawi-hijau', 'Tender and sweet Choy Sum harvested with early morning dew. Packed with calcium, iron, and dietary fiber.', 'Sawi hijau segar dengan batang manis dan rangup. Sesuai untuk masakan mee goreng, sup, dan tumis bawang putih.', '2026-09-02 05:00 AM', '2026-09-09', 320.00, 1.00, 'kg', 3.20, 4.80, '3°C - 5°C Moist wrap', 'Lunas, Kedah', 'Grade A Tender Stem', 'Biological Pest Control (Safe)', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80', 0, 'Crisp green stems picked at first light.', 'Essential leafy green for Malaysian home cooking.', 'FARM FRESH', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (8, 'AF-KLM-2026-056', 2, 7, 'Hydroponic Premium Baby Kailan', 'Baby Kailan Hidroponik Premium', 'hydroponic-premium-baby-kailan', 'Young, crunchy baby kailan shoots. Clean taste with no bitterness. Ideal for oyster sauce stir-fries.', 'Pucuk baby kailan hidroponik yang rangup dan manis tanpa rasa pahit. Pilihan utama restoran untuk kailan ikan masin.', '2026-09-02 06:15 AM', '2026-09-11', 140.00, 1.00, 'kg', 5.00, 7.80, '4°C Chilled', 'Kulim, Kedah', 'Grade A Tender Shoots', '100% Pesticide Free', 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&auto=format&fit=crop&q=80', 0, 'Restaurant grade tenderness.', 'Cultivated in Kulim''s protected indoor hydroponic greenhouse.', 'CHEF CHOICE', 'approved', '2026-09-02 20:37:05');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (9, 'AF-LUN-2026-254', 1, 1, 'Japanese Cucumber', 'Japanese Cucumber', 'japanese-cucumber', 'Harvest from the farm', 'Harvest from the farm', '2026-09-03 05:30 AM', NULL, 150.00, 1.00, 'kg', 2.50, 3.75, '4°C - 8°C Chilled', 'Lunas, Kedah', 'Grade A Premium', 'MyGAP Lab Tested (Safe 0.00 ppm)', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800', 0, NULL, NULL, 'NEW HARVEST', 'approved', '2026-09-04 01:47:58');
INSERT INTO products ("id", "batch_id", "farmer_id", "category_id", "name", "name_ms", "slug", "description", "description_ms", "harvest_date", "expiry_date", "quantity_available", "minimum_order", "unit", "price_per_unit", "middleman_price", "storage_temp", "farm_location", "grade", "pesticide_status", "image_path", "is_spotlight", "spotlight_headline", "spotlight_subtitle", "tag", "approval_status", "created_at") VALUES (10, 'AF-LUN-2026-265', 5, 2, 'Japanese Cucumber', 'Japanese Cucumber (Crispy Sweet)', 'japanese-cucumber', 'Locally grown premium cucumbers from Ladang Hijau Makmur.', 'Locally grown premium cucumbers from Ladang Hijau Makmur.', '2026-09-06 05:30 AM', NULL, 150.00, 1.00, 'kg', 3.50, 5.70, '4°C - 8°C Chilled', 'Lot 19, Jalan Wawasan, Kampung Bendang Dalam, 08400 Merbok, Kedah.', 'Grade A Premium', 'MyGAP Lab Tested (Safe 0.00 ppm)', 'assets/img/uploads/crop_1788683145_5873.webp', 0, NULL, NULL, 'FRESH HARVEST', 'approved', '2026-09-06 16:25:45');
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1));

-- Table: orders (7 rows)
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (1, NULL, 'ORD-KDH-8902', 'Restoran Selera Kedah (Lunas)', 'Commercial Buyer (Restaurant)', '+60 19-445 1928', 165.00, 'Out for Delivery', 'FPX Online Banking (Maybank)', 'Lot 14, Jalan Besar Lunas, 09600 Kedah', 'Morning delivery before 10 AM', 'AF-LUN-2026-089', 'Famox Express Logistics (Van KDH 4410)', '2026-09-02 20:37:05');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (2, NULL, 'ORD-KDH-8901', 'SMK Lunas School Canteen', 'Institutional Buyer (School)', '+60 17-332 9901', 198.00, 'Packed at Lunas Hub', 'DuitNow QR Instant Pay', 'Kantin SMK Lunas, Jalan Padang Serai, 09600 Kedah', 'Weekly fresh vegetables supply', 'AF-LUN-2026-012', 'Famox Cold-Van 2', '2026-09-02 20:37:05');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (3, NULL, 'ORD-KDH-8899', 'Nurul Aini Binti Yusof', 'Household Consumer', '+60 19-881 2244', 37.00, 'Delivered & QR Scanned', 'Credit Card (Visa)', 'No. 8, Taman Lunas Jaya, 09600 Lunas, Kedah', 'Leave with neighbour if not around', 'AF-FMX-2026-BOX1', 'Famox Direct Home Delivery', '2026-09-02 20:37:05');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (4, NULL, 'ORD-KDH-6360', 'Muhammad Aizat (Buyer)', 'Buyer', '+60 19-334 8812', 45.40, 'Order Confirmed & QR Tagged', 'FPX Online Banking (Maybank)', 'No. 12, Jalan Lunas Makmur 3, 09600 Lunas, Kedah', NULL, 'AF-FMX-2026-BOX1', 'Famox Logistics Lunas Hub (Van KDH 4410)', '2026-09-10 22:36:13');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (5, 9, 'ORD-KDH-9059', 'Paarteeban', 'Buyer', '019-8343847', 9.20, 'Order Confirmed & QR Tagged', 'FPX Online Banking (Maybank)', 'lot 129, jalan seroja, 08400 merbpok ,kedah', NULL, 'AF-LUN-2026-089', 'Famox Logistics Lunas Hub (Van KDH 4410)', '2026-09-11 10:35:57');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (6, 6, 'ORD-KDH-6520', 'Muhammad Aizat (Buyer)', 'Buyer', '+60 19-334 8812', 45.40, 'Order Confirmed & QR Tagged', 'FPX Online Banking (Maybank)', 'No. 12, Jalan Lunas Makmur 3, 09600 Lunas, Kedah', NULL, 'AF-LUN-2026-254', 'Famox Logistics Lunas Hub (Van KDH 4410)', '2026-09-13 01:15:35');
INSERT INTO orders ("id", "user_id", "order_number", "buyer_name", "buyer_role", "phone", "total_amount", "status", "payment_method", "shipping_address", "notes", "batch_code", "driver", "created_at") VALUES (7, 6, 'ORD-KDH-4356', 'Muhammad Aizat (Buyer)', 'Buyer', '+60 19-334 8812', 45.40, 'Order Confirmed & QR Tagged', 'FPX Online Banking (Maybank)', 'No. 12, Jalan Lunas Makmur 3, 09600 Lunas, Kedah', NULL, 'AF-LUN-2026-254', 'Famox Logistics Lunas Hub (Van KDH 4410)', '2026-09-22 02:30:26');
SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1));

-- Table: order_items (13 rows)
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (1, 1, 'Lunas Sweet Roma Tomatoes', 25.00, 'kg', 4.20, 105.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (2, 1, 'Kedah Kulim Cili Padi Merah', 5.00, 'kg', 12.00, 60.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (3, 2, 'Lunas Fresh Sawi Hijau (Choy Sum)', 40.00, 'kg', 3.20, 128.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (4, 2, 'Pokok Sena Crispy Cucumbers', 20.00, 'kg', 3.50, 70.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (5, 3, 'Famox Weekly Harvest Box (6kg Bundle)', 1.00, 'box', 28.00, 28.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (6, 3, 'Hydroponic Butterhead Lettuce', 2.00, 'pack', 4.50, 9.00, '2026-09-02 20:37:05');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (7, 4, 'Famox Weekly Harvest Box (6kg Bundle)', 1.00, 'box (6kg assorted)', 28.00, 28.00, '2026-09-11 06:36:13');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (8, 4, 'Pokok Sena Crispy Cucumbers', 1.00, 'kg', 3.50, 3.50, '2026-09-11 06:36:13');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (9, 5, 'Lunas Sweet Roma Tomatoes', 1.00, 'kg', 4.20, 4.20, '2026-09-11 10:35:57');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (10, 6, 'Japanese Cucumber', 1.00, 'kg', 2.50, 2.50, '2026-09-13 09:15:35');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (11, 6, 'Hydroponic Premium Baby Kailan', 1.00, 'kg', 5.00, 5.00, '2026-09-13 09:15:35');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (12, 7, 'Japanese Cucumber', 2.00, 'kg', 2.50, 5.00, '2026-09-22 10:30:26');
INSERT INTO order_items ("id", "order_id", "product_name", "quantity", "unit", "price", "subtotal", "created_at") VALUES (13, 7, 'Hydroponic Premium Baby Kailan', 1.00, 'kg', 5.00, 5.00, '2026-09-22 10:30:26');
SELECT setval(pg_get_serial_sequence('order_items', 'id'), COALESCE((SELECT MAX(id) FROM order_items), 1));

-- Table: price_index (6 rows)
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (1, 'Roma Tomatoes (Lunas)', 4.20, 6.80, '+42%', 'Stable', '2026-09-02 20:37:05');
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (2, 'Hydroponic Butterhead (Kulim)', 4.50, 7.20, '+48%', 'Up 5%', '2026-09-02 20:37:05');
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (3, 'Sweet Honey Corn (Baling)', 2.20, 3.80, '+38%', 'Stable', '2026-09-02 20:37:05');
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (4, 'Cili Padi Kampung (Kulim)', 12.00, 18.50, '+45%', 'High Demand', '2026-09-02 20:37:05');
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (5, 'Sawi Hijau (Lunas)', 3.20, 4.80, '+35%', 'Stable', '2026-09-02 20:37:05');
INSERT INTO price_index ("id", "crop_name", "direct_price", "middleman_price", "farmer_gain", "trend", "updated_at") VALUES (6, 'Baby Kailan Hidro (Kulim)', 5.00, 7.80, '+40%', 'Up 3%', '2026-09-02 20:37:05');
SELECT setval(pg_get_serial_sequence('price_index', 'id'), COALESCE((SELECT MAX(id) FROM price_index), 1));

-- Table: activity_logs (48 rows)
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (1, 'Pak Cik Azman', 'New Crop Batch Listed', 'Registered AF-LUN-2026-089 (Roma Tomatoes) with QR generation', '127.0.0.1', '2026-09-02 20:37:05');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (2, 'Famox Hub QC', 'MyGAP Verification Passed', 'Lab tested 0.00 ppm pesticide residue for Kulim Hydroponic batch', '127.0.0.1', '2026-09-02 20:37:05');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (3, 'Restoran Selera Kedah', 'Order Checkout Completed', 'Placed order ORD-KDH-8902 with FPX payment', '127.0.0.1', '2026-09-02 20:37:05');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (4, 'System', 'Daily Price Index Synced', 'Updated Kedah Fair Trade wholesale indices', '127.0.0.1', '2026-09-02 20:37:05');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (5, 'Muhammad Aizat Izzuddin', 'New Account Registered', 'Registered as Buyer', '::1', '2026-09-04 01:31:27');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (6, 'Aina Izzati Binti Azmi', 'New Account Registered', 'Registered as Farmer', '::1', '2026-09-04 01:47:08');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (7, 'Aina Izzati Binti Azmi', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-04 06:58:50');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (8, 'Pak Cik Azman Bin Hashim', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-04 07:52:20');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (9, 'Aina Izzati Binti Azmi', 'User Signed In (Laravel)', 'Signed in as Farmer', '127.0.0.1', '2026-09-04 09:39:07');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (10, 'Aina Izzati Binti Azmi', 'User Signed In (Laravel)', 'Signed in as Farmer', '127.0.0.1', '2026-09-04 09:43:41');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (11, 'Aina Izzati Binti Azmi', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-06 16:24:29');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (12, 'Famox Admin (Lunas Hub)', 'User Signed In', 'Signed in as Administrator', '::1', '2026-09-08 23:16:04');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (13, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-08 23:16:30');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (14, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-08 23:25:01');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (15, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-08 23:56:16');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (16, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-08 23:56:16');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (17, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-08 23:56:17');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (18, 'Famox Admin (Lunas Hub)', 'User Signed In', 'Signed in as Administrator', '::1', '2026-09-09 00:01:00');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (19, 'Pak Cik Azman Bin Hashim', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-09 00:01:14');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (20, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-09 00:01:29');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (21, 'Pak Cik Azman Bin Hashim', 'User Signed In (Laravel)', 'Signed in as Farmer', '127.0.0.1', '2026-09-09 00:01:52');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (22, 'Pak Cik Azman Bin Hashim', 'User Signed In (Laravel)', 'Signed in as Farmer', '127.0.0.1', '2026-09-09 00:02:02');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (23, 'Famox Admin (Lunas Hub)', 'User Signed In (Laravel)', 'Signed in as Administrator', '127.0.0.1', '2026-09-09 00:02:11');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (24, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-09 00:02:22');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (25, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '::1', '2026-09-09 00:12:26');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (26, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-10 15:25:44');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (27, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-10 15:46:16');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (28, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-10 15:46:26');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (29, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-11 06:35:43');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (30, 'Muhammad Aizat (Buyer)', 'Order Placed (Laravel)', 'Placed order ORD-KDH-6360 (RM 45.40)', '127.0.0.1', '2026-09-11 06:36:13');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (31, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-11 06:37:44');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (32, 'Pak Cik Azman Bin Hashim', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-11 06:46:30');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (33, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-11 07:18:11');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (34, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-11 07:35:22');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (35, 'Pak Cik Azman Bin Hashim', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-11 07:35:43');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (36, 'Famox Admin (Lunas Hub)', 'User Signed In', 'Signed in as Administrator', '::1', '2026-09-11 07:35:58');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (37, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-11 07:55:48');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (38, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-11 08:19:55');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (39, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-11 08:42:13');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (40, 'Paarteeban', 'New Account Registered', 'Registered as Buyer', '::1', '2026-09-11 10:35:25');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (41, 'Paarteeban', 'Order Placed & Paid', 'Completed checkout for order ORD-KDH-9059 (RM 9.20)', '::1', '2026-09-11 10:35:57');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (42, 'Pak Cik Azman Bin Hashim', 'User Signed In (Laravel)', 'Signed in as Farmer', '127.0.0.1', '2026-09-13 09:06:11');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (43, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-13 09:10:40');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (44, 'Muhammad Aizat (Buyer)', 'Order Placed (Laravel)', 'Placed order ORD-KDH-6520 (RM 45.40)', '127.0.0.1', '2026-09-13 09:15:35');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (45, 'Muhammad Aizat (Buyer)', 'User Signed In', 'Signed in as Buyer', '::1', '2026-09-22 06:25:18');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (46, 'Muhammad Aizat (Buyer)', 'User Signed In (Laravel)', 'Signed in as Buyer', '127.0.0.1', '2026-09-22 06:25:25');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (47, 'Aina Izzati Binti Azmi', 'User Signed In', 'Signed in as Farmer', '::1', '2026-09-22 10:27:41');
INSERT INTO activity_logs ("id", "user_name", "action", "description", "ip_address", "created_at") VALUES (48, 'Muhammad Aizat (Buyer)', 'Order Placed (Laravel)', 'Placed order ORD-KDH-4356 (RM 45.40)', '127.0.0.1', '2026-09-22 10:30:26');
SELECT setval(pg_get_serial_sequence('activity_logs', 'id'), COALESCE((SELECT MAX(id) FROM activity_logs), 1));

